/data/group1/z40351r/VoiceActivityProjection/.d0001062536: line 12: exp_dir: command not found
Load Model...
From state-dict:  /best_model.pt
########################################
Load pretrained CPC
########################################
Froze EncoderCPC!
Traceback (most recent call last):
  File "/data/group1/z40351r/VoiceActivityProjection/run.py", line 200, in <module>
    sd = torch.load(args.state_dict)
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/best_model.pt'
