Global seed set to 1
########################################
Load pretrained CPC
########################################
Froze EncoderCPC!
DataConfig(train_path='None', val_path='None', test_path='../vap_dataset/data/sliding_test.csv', conf_path='exp/callhome_eng/dset_conf.yaml', flip_channels=True, flip_probability=0.5, mask_vad=True, mask_vad_probability=0.5, batch_size=16, num_workers=24, audio_duration=20)
Traceback (most recent call last):
  File "/data/group1/z40351r/VoiceActivityProjection/vap/train.py", line 529, in <module>
    train()
  File "/data/group1/z40351r/VoiceActivityProjection/vap/train.py", line 171, in train
    data_conf = DialogAudioDM.load_config(dconf.conf_path)
  File "/data/group1/z40351r/datasets_turntaking/datasets_turntaking/dialog_audio_dm.py", line 311, in load_config
    return load_config(path, args=args, format=format)
  File "/data/group1/z40351r/datasets_turntaking/datasets_turntaking/utils.py", line 162, in load_config
    conf = OmegaConf.load(path)
  File "/home/z40351r/anaconda3/envs/vap2/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/group1/z40351r/VoiceActivityProjection/exp/callhome_eng/dset_conf.yaml'
